name: Conditions
on: push
jobs:
  skip-or-run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello"
        if: ${{ contains(github.run_id, '1') }}
      - run: echo github1 "${github.run_id}"
      - run: echo github2 ${{github.run_id}}
